# Generated by Django 5.1.3 on 2024-11-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0001_initial'),
        ('user_honey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_honey.userhoney'),
            preserve_default=False,
        ),
    ]
