# Generated by Django 5.1.3 on 2024-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honey_app', '0002_comment_user'),
        ('user', '0001_initial'),
        ('user_honey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='honeys',
            field=models.ManyToManyField(help_text='Honey by user', related_name='users', through='user_honey.UserHoney', to='honey_app.honey'),
        ),
    ]
